### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by bryant0918** [PedroDKE/LibriS2S#1]
I am trying to download the data but when I click on the onedrive link it says it has been removed or no longer exists.

**Comment by PedroDKE** [comment]
Hi,

i've just updated the outlook link, i hope that it works now! Else you can try trough huggingface and let me know if that works or not? Note, outlook will display a warning that a preview can not be given

**Comment by bryant0918** [comment]
Yep it works now. Thanks

**Comment by bryant0918** [comment]
@PedroDKE If you get rid of the .git folder in the LibriS2S.zip folder on your OneDrive link that would remove 32 GB of unneeded storage by anyone interesting in downloading this dataset, which would then make it much easier and quicker to download.

**Comment by PedroDKE** [comment]
@bryant0918  Nice catch! Uploaded a new zip file. Thanks
